version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20

  pre_build:
    commands:
      - echo "Hello from pre_build"

  build:
    commands:
      - echo "Hello from build"

  post_build:
    commands:
      - echo "Hello from post_build"

artifacts:
  files:
    - '**/*'
