version: 0.2

env:
  variables:
    PROJECT_NAME: "aws-devops"
    ENV: "prod"
    IMAGE_TAG: "latest"
    PRIMARY_REGION: "us-east-1"
    SECONDARY_REGION: "us-east-2"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR in primary region...
      - PRIMARY_REPO_URL=$(aws ecr describe-repositories --region $PRIMARY_REGION --repository-names ${PROJECT_NAME}-${ENV} --query 'repositories[0].repositoryUri' --output text)
      - aws ecr get-login-password --region $PRIMARY_REGION | docker login --username AWS --password-stdin $PRIMARY_REPO_URL
      - echo Logging in to Amazon ECR in secondary region...
      - SECONDARY_REPO_URL=$(aws ecr describe-repositories --region $SECONDARY_REGION --repository-names ${PROJECT_NAME}-${ENV} --query 'repositories[0].repositoryUri' --output text)
      - aws ecr get-login-password --region $SECONDARY_REGION | docker login --username AWS --password-stdin $SECONDARY_REPO_URL

  build:
    commands:
      - echo Building Docker image...
      - docker build -t app:$IMAGE_TAG src/
      - echo Tagging image for primary region...
      - docker tag app:$IMAGE_TAG $PRIMARY_REPO_URL:$IMAGE_TAG
      - echo Tagging image for secondary region...
      - docker tag app:$IMAGE_TAG $SECONDARY_REPO_URL:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing image to primary ECR...
      - docker push $PRIMARY_REPO_URL:$IMAGE_TAG
      - echo Pushing image to secondary ECR...
      - docker push $SECONDARY_REPO_URL:$IMAGE_TAG
      - echo Forcing ECS deployment in primary region...
      - aws ecs update-service --region $PRIMARY_REGION --cluster ${PROJECT_NAME}-${ENV}-cluster-primary --service ${PROJECT_NAME}-${ENV}-svc-primary --force-new-deployment
      - echo Forcing ECS deployment in secondary region...
      - aws ecs update-service --region $SECONDARY_REGION --cluster ${PROJECT_NAME}-${ENV}-cluster-secondary --service ${PROJECT_NAME}-${ENV}-svc-secondary --force-new-deployment

artifacts:
  files:
    - '**/*'
